module.exports = [
  //{title:"plain", name:"plain"},
  //{title:"functional", name:"functional"},
  //{title:"callback", name:"callback"},
  //{title:"link", name:"link"},
  //{title:"color", name:"color"},
  //{title:"ruby", name:"ruby"},
  //{title:"section", name:"section"},
  //{title:"pasted-attribute", name:"pasted-attribute"},
  //{title:"tip-test", name:"tip-test"},
  //{title:"speak-test", name:"speak-test"},
  //{title:"gravatar-test", name:"gracatar-test"},
  {title:"pseudo-element", name:"pseudo-element"},
  {title:"pseudo-class", name:"pseudo-class"},
  {title:"border-radius", name:"border-radius"},
  {title:"selector test", name:"selector"},
  {title:"flip-flow", name:"flip-flow"},
  {title:"circular", name:"circular"},
  {title:"animated clock", name:"clock"},
  {title:"mathjax", name:"mathjax"},
  {title:"table", name:"table"},
  {title:"table-auto", name:"table-auto"},
  {title:"float", name:"float"},
  //{title:"float-clear-start", name:"float-clear-start"},
  //{title:"float-clear-end", name:"float-clear-end"},
  //{title:"float-clear-both", name:"float-clear-both"},
  {title:"baseline", name:"baseline"},
  {title:"list", name:"list"},
  {title:"text-align", name:"text-align"},
  {title:"iblock", name:"iblock"},
  {title:"pre", name:"pre"},
  {title:"page-break", name:"page-break"},
  {title:"hr", name:"hr"},
  {title:"kerning", name:"kerning"},
  {title:"text-combine-upright", name:"text-combine-upright"},
  {title:"text-orientation", name:"text-orientation"},
  {title:"inline-img", name:"inline-img"},
  {title:"empha", name:"empha"},
  {title:"header", name:"header"},
  {title:"push-pull", name:"push-pull"},
  {title:"margin-cancel", name:"margin-cancel"},
  {title:"word-break", name:"word-break"},
  {title:"prettify", name:"prettify"},
  {title:"white-space", name:"white-space"}
];
